
package Formularios;

import Clases.Boletos;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fabri
 */
public class frmNuevoC extends javax.swing.JFrame {

       public ArrayList<Boletos> listaboleto;

    public frmNuevoC() {
        initComponents();
        
        listaboleto=new ArrayList<>();
        this.setLocationRelativeTo(null);
        
        TextPrompt referencias1 = new TextPrompt("INGRESE EL CODIGO", txtcodboleto);
        TextPrompt referencias2 = new TextPrompt("INGRESE CODIGO DE AVION", txtcodavion);
        TextPrompt referencias3 = new TextPrompt("INGRESE NOMBRE COMPLETO", txtnombreboleto);
        TextPrompt referencias4 = new TextPrompt("INGRESE EL DESTINO", txtdestino);
        TextPrompt referencias5 = new TextPrompt("INGRESE EL PRECIO", txtprecio);
        
    }
        public void listamostrar(){
    DefaultListModel modelo =new DefaultListModel();
    for (int i=0; i<listaboleto.size(); i++){
        modelo.addElement(listaboleto.get(i).getCodBoleto()+" ||  "+listaboleto.get(i).getNombre()+" || "+listaboleto.get(i).getCodAvion()+" || "+listaboleto.get(i).getAsiento()+" || "+listaboleto.get(i).getDestino()+"   || "+listaboleto.get(i).getClaseViaje()+" || "+listaboleto.get(i).getPrecio());
    }
    lsBoleto.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txtcodboleto = new javax.swing.JTextField();
        txtcodavion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comClase = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comAsiento = new javax.swing.JComboBox<>();
        txtnombreboleto = new javax.swing.JTextField();
        txtdestino = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsBoleto = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel9.setText("BOLETOS ");

        txtcodboleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodboletoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel12.setText("CLASE DE VUELO");

        comClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLASE TURISTA", "CLASE MEDIA", "CLASE ALTA" }));
        comClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comClaseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("N ASIENTO");

        comAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lsBoleto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54)
                                .addComponent(comAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodavion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcodboleto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombreboleto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comClase, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtcodboleto, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtcodavion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombreboleto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodboletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodboletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodboletoActionPerformed

    private void comClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comClaseActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
         Boletos boleto=new Boletos();
         String Codbole;
    String nombreB;
    String asiento; 
     int asientop=0;
     String Codavip;
     String destip;
     String vuelIda;
     String vueloVeni;
     String clase;
     String preciop;
     double precio=0;
     Codbole=txtcodboleto.getText();
     nombreB=txtnombreboleto.getText();
     Codavip=txtcodavion.getText();
     asiento=comAsiento.getSelectedItem().toString();
     
         try{
     asientop=Integer.parseInt(asiento);
     } catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null,"EL DATO DEBE SER NUMERICO","ERROR",JOptionPane.ERROR_MESSAGE);
         
     }
     destip=txtdestino.getText();
     clase=comClase.getSelectedItem().toString();
     preciop=txtprecio.getText();
        try{
     precio=Integer.parseInt(preciop);
     } catch(NumberFormatException e){
         JOptionPane.showMessageDialog(null,"EL DATO DEBE SER NUMERICO","ERROR",JOptionPane.ERROR_MESSAGE);
         
     }
     boleto.setCodBoleto(Codbole);
     boleto.setNombre(nombreB);
     boleto.setCodAvion(Codavip);
     boleto.setAsiento(asientop);
     boleto.setDestino(destip);
     boleto.setClaseViaje(clase);
     boleto.setPrecio(precio);
        
    
    listaboleto.add(boleto);
    JOptionPane.showMessageDialog(null,"REGISTRO AGREGADO","AGREGAR",JOptionPane.INFORMATION_MESSAGE);
    listamostrar();
       txtcodboleto.setText(null);
        txtnombreboleto.setText(null);
        txtcodavion.setText(null);
        txtdestino.setText(null);
     txtprecio.setText(null);
     comAsiento.setToolTipText(null);
     
    }                                          

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        //String nom = JOptionPane.showInputDialog ( "INGRESE EL NOMBRE A BUSCAR:" );
        int row=lsBoleto.getSelectedIndex();
        if (row==-1){
            JOptionPane.showMessageDialog(null,"SELLECIONE UN ELEMENTO DE LA LISTA","AVISO",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
         JOptionPane.showMessageDialog(null,listaboleto.get(row).getDatos(),"MOSTAR",JOptionPane.PLAIN_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNuevoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNuevoC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> comAsiento;
    private javax.swing.JComboBox<String> comClase;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lsBoleto;
    private javax.swing.JTextField txtcodavion;
    private javax.swing.JTextField txtcodboleto;
    private javax.swing.JTextField txtdestino;
    private javax.swing.JTextField txtnombreboleto;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
